"""
ACP多Agent协作示例
演示：新闻Agent -> 分析Agent -> 部署Agent 的工作流
"""
import asyncio
from acp import Agent, WorkflowEngine, WorkflowStep, WorkflowStatus, MessageBusFactory


async def main():
    # 创建共享的消息总线
    message_bus = MessageBusFactory.create("memory")
    
    # 创建新闻Agent
    news_agent = Agent(
        name="news-agent",
        capabilities=["fetch_news", "search_news"],
        message_bus=message_bus
    )
    
    @news_agent.handler("fetch_news")
    async def handle_fetch_news(request):
        symbol = request.parameters.get("symbol", "AAPL")
        print(f"[NewsAgent] Fetching news for {symbol}...")
        await asyncio.sleep(0.5)  # 模拟网络请求
        return {
            "symbol": symbol,
            "headlines": [
                f"{symbol} announces record quarterly earnings",
                f"Analysts upgrade {symbol} price target",
                f"{symbol} expands into new markets"
            ],
            "sentiment": "positive"
        }
    
    @news_agent.handler("search_news")
    async def handle_search_news(request):
        query = request.parameters.get("query", "")
        return {
            "query": query,
            "results": [f"News about {query}"]
        }
    
    # 创建分析Agent
    analyzer_agent = Agent(
        name="analyzer-agent",
        capabilities=["stock_analysis", "sentiment_analysis"],
        message_bus=message_bus
    )
    
    @analyzer_agent.handler("stock_analysis")
    async def handle_stock_analysis(request):
        symbol = request.parameters.get("symbol", "AAPL")
        news_data = request.parameters.get("news_data", {})
        
        print(f"[AnalyzerAgent] Analyzing {symbol}...")
        await asyncio.sleep(0.5)
        
        sentiment = news_data.get("sentiment", "neutral")
        recommendation = "buy" if sentiment == "positive" else "hold"
        
        return {
            "symbol": symbol,
            "recommendation": recommendation,
            "confidence": 0.85,
            "sentiment": sentiment,
            "headlines_analyzed": len(news_data.get("headlines", []))
        }
    
    @analyzer_agent.handler("sentiment_analysis")
    async def handle_sentiment_analysis(request):
        text = request.parameters.get("text", "")
        return {
            "text": text,
            "sentiment": "positive" if "good" in text.lower() else "neutral"
        }
    
    # 创建部署Agent
    deploy_agent = Agent(
        name="deploy-agent",
        capabilities=["deploy_report", "generate_html"],
        message_bus=message_bus
    )
    
    @deploy_agent.handler("deploy_report")
    async def handle_deploy_report(request):
        analysis_data = request.parameters.get("analysis_data", {})
        
        print(f"[DeployAgent] Deploying report...")
        await asyncio.sleep(0.3)
        
        symbol = analysis_data.get("symbol", "UNKNOWN")
        recommendation = analysis_data.get("recommendation", "hold")
        
        report_html = f"""
        <html>
        <body>
            <h1>Stock Analysis Report: {symbol}</h1>
            <p>Recommendation: <strong>{recommendation.upper()}</strong></p>
            <p>Confidence: {analysis_data.get('confidence', 0) * 100}%</p>
            <p>Generated by ACP Multi-Agent System</p>
        </body>
        </html>
        """
        
        return {
            "report_id": f"report_{symbol.lower()}",
            "symbol": symbol,
            "url": f"https://reports.example.com/{symbol.lower()}",
            "html": report_html,
            "status": "deployed"
        }
    
    @deploy_agent.handler("generate_html")
    async def handle_generate_html(request):
        data = request.parameters.get("data", {})
        return {
            "html": f"<div>{data}</div>"
        }
    
    # 启动所有Agent
    await news_agent.start()
    await analyzer_agent.start()
    await deploy_agent.start()
    
    print("\n" + "="*50)
    print("ACP Multi-Agent Demo Started")
    print("="*50 + "\n")
    
    # 创建工作流引擎
    engine = WorkflowEngine()
    engine.register_agent(news_agent)
    engine.register_agent(analyzer_agent)
    engine.register_agent(deploy_agent)
    
    # 定义工作流：获取新闻 -> 分析股票 -> 部署报告
    steps = [
        WorkflowStep(
            step_id="fetch_news",
            task_type="fetch_news",
            agent_name="news-agent",
            parameters={"symbol": "TSLA"}
        ),
        WorkflowStep(
            step_id="analyze_stock",
            task_type="stock_analysis",
            agent_name="analyzer-agent",
            parameters={
                "symbol": "TSLA",
                "news_data": "$results.fetch_news"  # 引用上一步结果
            },
            depends_on=["fetch_news"]
        ),
        WorkflowStep(
            step_id="deploy_report",
            task_type="deploy_report",
            agent_name="deploy-agent",
            parameters={
                "analysis_data": "$results.analyze_stock"  # 引用分析结果
            },
            depends_on=["analyze_stock"]
        )
    ]
    
    # 创建工作流并执行
    workflow = engine.create_workflow("stock_analysis_pipeline", steps)
    result = await engine.execute_workflow(workflow)
    
    # 输出结果
    print("\n" + "="*50)
    print("Workflow Execution Result")
    print("="*50)
    print(f"Workflow ID: {result.workflow_id}")
    print(f"Status: {result.status.value}")
    print(f"\nStep Results:")
    for step_id, step_result in result.results.items():
        print(f"  {step_id}: {step_result}")
    
    if result.errors:
        print(f"\nErrors:")
        for step_id, error in result.errors.items():
            print(f"  {step_id}: {error}")
    
    # 输出Agent统计
    print("\n" + "="*50)
    print("Agent Statistics")
    print("="*50)
    for agent in [news_agent, analyzer_agent, deploy_agent]:
        stats = agent.get_stats()
        print(f"\n{agent.name}:")
        print(f"  Tasks received: {stats['tasks_received']}")
        print(f"  Tasks completed: {stats['tasks_completed']}")
        print(f"  Messages sent: {stats['messages_sent']}")
        print(f"  Messages received: {stats['messages_received']}")
    
    # 停止所有Agent
    await news_agent.stop()
    await analyzer_agent.stop()
    await deploy_agent.stop()
    await message_bus.close()
    
    print("\n" + "="*50)
    print("Demo Completed")
    print("="*50)


if __name__ == "__main__":
    asyncio.run(main())
